name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3d5670701dbb936f18f7fa13f489c942b260b4e0b0d96980ab097166a3570bf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
