name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "817172a4aac2aaaa9a15bf8ce652cc7e3b83c1143a734b80f073d5a290e56897"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
