name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045316b3b5286ec39d40a52fe6be02d39cb7ebc4dd6924f9e37714da180494ce"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
