name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca6c4d014df38fe998beb54a347abed649e803c4f211e77bb9bcd4b145d004a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
