name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b91b0e48911c809254d8b277e37cf43716e19e4ad3cca27da3ec1f3e482f8c8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
