name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "587b4f9d535097ae9af8e703c9cc94225fb3964f7126b3d9d5c79c8d04f104bb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
