name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c71bdabe07b458f52162819ae7c7a5ec1be3bbba019c8a95f485b7fc9435a676"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
