name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c128b5fd5bf2242bf0d3d6a88ee5c7c489294859bc8ab739208695bc9ff82f19"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
