name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44199cca1d374399a296148286090a4dca2958af2f080ed1e3849efafcd5cf10"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
