name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0229ffc2ecb30d7722dd89a90e2ac556c83d59b27abf62e65af4a873ef75a6a3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
